name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go 1.22
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
    - name: Run tests
      run: go test -v ./...
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: garaekz/ozzo-routing
